### ISSUE TITLE
Zaključek projekta, težave pri Binderju

### ISSUE THREAD

**Issue by LeaHolc** [nikapavlic/Recepcija#1]
Pozdravljeni,

projekt je pripravljen za oddajo, vendar pa imamo težave pri Binderju. Poskusile smo ga narediti vendar nam javlja napako, za katero samo ugibamo, da je povezana z datoteko requirements.txt. Prosile bi za nekaj pomoči oz. kakšen nasvet, kako narediti Binder.

Hvala že v naprej!

**Comment by majbc1999** [comment]
Živjo,

sem se nekaj trudil z Binderjem, ampak nisem nič prav pametnega (še) ugotovil. Kar se tiče projekta sem preveril registracijo in funkcionalnost aplikacije za gosta in vse štima. Rabil bi še uporabniško ime in geslo nekega receptorja, da lahko preverim še delovanje zanj. Prosim, dodajte te podatke tudi v `README`, da bo znal vašo aplikacijo uporabljati kdorkoli. 

Bom poskusil med vikendom še kaj pogledati za Binder.

**Comment by nikapavlic** [comment]
Pozdravljeni, 

Najlepša hvala!

Uporabniško ime in geslo glavnega receptorja:
uporabniško ime: receptor
geslo: receptor

Uporabniško ime in geslo navadnega receptorja (vse je enako, ti le nimajo možnosti vpogleda do vseh receptorjev):
uporabniško ime: nikapavlic
geslo: pomlad02

**Comment by majbc1999** [comment]
Živjo,

sedaj sem malo bolj podobno pregledal vaš projekt in imam še par težav, ki jih je potrebno odpraviti pred ustnim zagovorom:

- Gesla zaposlenih zaenkrat v bazo shranjujete v hashirani obliki. To je tudi prav, ampak potem pri prijavi primerjate z nehashiranim geslom. Zato prijava ne dela za novo ustvarjene uporabnike.
- Dobra programerska praksa je, da ko Pythonu (ali tudi v drugih jezikih) uporabljate `try-except` stavek, tudi specifično izrazite kateri exception v stavku lovite. Na primer: 
```python
try:
        hashBaza = cur.execute(
            "SELECT geslo FROM receptor WHERE uporabnisko_ime = %s", [uporabnisko_ime])
        hashBaza = cur.fetchone()[0]
        id_receptorja = cur.execute(
            "SELECT emso FROM receptor WHERE uporabnisko_ime = %s", [uporabnisko_ime])
        id_receptorja = cur.fetchall()[0]
    except:
        hashBaza = None
```
Tukaj želimo uloviti `TypeError` (ki ga pričakujemo). Tako kot imate sedaj narejeno, pa bo tudi npr. `ConnectionError` ujet v except stavek. Aplikacija bo tako uporabniku javila, da je vpisal napačno uporabniško ime, čeprav bodo težave v resnici drugje. Varnejše bo torej:
 ```python
try:
        hashBaza = cur.execute(
            "SELECT geslo FROM receptor WHERE uporabnisko_ime = %s", [uporabnisko_ime])
        hashBaza = cur.fetchone()[0]
        id_receptorja = cur.execute(
            "SELECT emso FROM receptor WHERE uporabnisko_ime = %s", [uporabnisko_ime])
        id_receptorja = cur.fetchall()[0]
    except TypeError:
        hashBaza = None
```  

Sicer pa je projekt res dobro narejen, pohvalno! Ko odpravite te probleme, mi javite, da še enkrat pregledam in odobim projekt. Jaz pa bom poskusil še usposobiti Binder.

**Comment by LeaHolc** [comment]
Živjo,

hvala za vsa opozorila; torej težave smo sedaj odpravile: edino starih receptorjev, ki gesel še nimajo hashiranih nismo dale ven iz baze, saj so vezani na račune, ti pa na rezervacije. Prijava s starim uporabniškim imenom in geslom reeptorja pač ni več mogoča. Zato smo ustvarile novega: "vodilnega" receptorja:
uporabniško_ime: vodja
geslo: vodja
Popravile smo tudi try- except stavek kot ste svetovali.

Hvala še enkrat!

**Comment by majbc1999** [comment]
Živjo, vidim da sedaj vse dela tako kot mora. Lahko se z @jaanos zmenite za ustni izpit. Jaz bom sicer še malo pogledal Binder, ampak mi res ni jasno zakaj noče pognati.

**Comment by spela-1** [comment]
Živjo, opazile smo kaj je bila napaka, zaradi katere Binder ni želel pognati. Sedaj dela kot bi moralo.

**Comment by majbc1999** [comment]
Super, srečno na zagovoru! 😃
